### ISSUE TITLE
There are no items, mod isn't showing?

### ISSUE THREAD

**Issue by katubug** [TalonsOfStealth/player-shops#1]
Hi, I'm having a weird issue with this where the mod seems to be installed correctly, but searching @player in JEI or Creative menu doesn't bring anything up. I also tried searching for "shop" and again, nothing.

I am able to /give myself the items, but they don't show up in any menus.

Forge 47.2.0
PlayerShops 1.2.0

**Comment by TalonsOfStealth** [comment]
This is a know issues, I'm working on it, I'll hopefully have a patch out today, in the mean time you can use /give @s playershops:XXXX_player_shop where XXXX is the wood type in lowercase

**Comment by TalonsOfStealth** [comment]
A new patch is out that fixes your issue
