### ISSUE TITLE
Project Distribution is disabled and is useless for servers

### ISSUE THREAD

**Issue by mcusercurseaternos** [TalonsOfStealth/player-shops#4]
Hello, i am writing about this issue because it doesn't allow project distribution. The server service I am using is _Aternos_.
**Screenshot Proof:**
![image](https://github.com/TalonsOfStealth/player-shops/assets/162926312/1b68bbb8-29e4-4b20-b214-86704b9562b6)

I am waiting for a response.

**Comment by TalonsOfStealth** [comment]
The mod should now be available for download.
